name: Build Android Release APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.4'
    - name: Generate Keystore
      run: |
        rm -f app/release.jks
        keytool -genkey -v -keystore app/release.jks -keyalg RSA -keysize 2048 -validity 10000 -alias upwell-key -dname "cn=UpwellClick, ou=App, o=UpwellClick, c=RU" -storepass upwellclick -keypass upwellclick
    - name: Build with Gradle
      run: gradle assembleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AutoClicker-Release-APK
        path: app/build/outputs/apk/release/*.apk
    - name: Upload Keystore
      uses: actions/upload-artifact@v4
      with:
        name: UpwellClick-Keystore
        path: app/release.jks
